all:
	gcc -g -Wall -O2 -I/gscuser/dlarson/src/samtools/trunk/samtools/ sniper_pileup.c sniper_maqcns.c somatic_sniper.c -o bam-somaticsniper -lm -lz -L/gscuser/dlarson/src/samtools/trunk/samtools -lbam
